import React from 'react';
import { Image } from 'semantic-ui-react';
import Banner from '../common/banner';
import '../../assets/scss/discovery.scss';

const banner = [
  {
    "imageUrl": "http://p1.music.126.net/U_3gIQShCOAxK7MPfJvRHg==/109951164579584348.jpg",
    "targetId": 1412022850,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1412022850",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.619319.1718617408.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/ec2Wqaggr0qLJ0F3GGBmuw==/109951164580721478.jpg",
    "targetId": 1411558182,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1411558182",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.622319.1718499338.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/7mLtHOqZSHShzw7uRbvv8A==/109951164579800036.jpg",
    "targetId": 10907888,
    "adid": null,
    "targetType": 1004,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "10907888",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.621325.1718466540.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/ZP3Bm8u3uAX7r37FFuKjIw==/109951164579620196.jpg",
    "targetId": 1411798801,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "VIP专享",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1411798801",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.623324.1718530981.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/VL3VWiIh8CmYGfb7R0PXlQ==/109951164579943540.jpg",
    "targetId": 84363964,
    "adid": null,
    "targetType": 10,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "84363964",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.623329.1718612666.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/q-czd4Wo1zgeOCvnZZTraA==/109951164579623696.jpg",
    "targetId": 1412013401,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1412013401",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.623326.1718468485.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/Ul4yeRpJOyZQrjJJ0vgbJw==/109951164579793921.jpg",
    "targetId": 1412022808,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1412022808",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.622326.1718471341.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/Vo2FIOAPufNW_1ixiUzz6A==/109951164579626193.jpg",
    "targetId": 1409320608,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "独家",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "1409320608",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.618342.1718621414.null"
  },
  {
    "imageUrl": "http://p1.music.126.net/BqNXkPUdb4q9WSOBUynaXw==/109951164579700862.jpg",
    "targetId": 2064614739,
    "adid": null,
    "targetType": 1001,
    "titleColor": "red",
    "typeTitle": "电台",
    "url": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": null,
    "monitorClickList": null,
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "adDispatchJson": null,
    "encodeId": "2064614739",
    "program": null,
    "event": null,
    "video": null,
    "song": null,
    "scm": "1.music-homepage.homepage_banner_force.banner.620317.1718553215.null"
  }
];

const color = {
  'red': '#db2828'
};

function Discovery() {
  return (
    <Banner>
      {
        banner.map((item, i) => (
          <div key={i} className='swiper-slide banner-item'>
            <Image src={item.imageUrl} rounded />
            <div className='title' style={{ background: color[item.titleColor] }}>{item.typeTitle}</div>
          </div>
        ))
      }
    </Banner>
  );
}

export default Discovery;
